version: 0.0
os: linux 
files: 
 - source: /index.html
   destination: /var/www/html
hooks:
  BeforeInstall:
   - location: scripts/deps.txt
     timeout: 300
     runas: root
   - location: scripts/dep.txt
     timeout: 300
     runas: root 
